#!/bin/sh

# cleanup
rm -rf obj_dir
rm -f top.vcd

# run Verilator to translate Verlig into C++, including C++ testbench
verilator -Wall --cc --trace top.sv --exe top_tb.cpp

# build C++ project via make file automatically generated by Verilator
make -j -C obj_dir/ -f Vtop.mk Vtop

# run the executable simulation file
obj_dir/Vtop